version: '3.8'

services:
  text-summarization-api:
    build: .
    ports:
      - "9000:9000"
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-llama-3.1-sonet-large-128k-online}
      - MAX_TOKENS=${MAX_TOKENS:-4000}
      - TEMPERATURE=${TEMPERATURE:-0.3}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
